version: "3"
services:
  minio:
    image: "minio/minio"
    command: server /data --address ":9000" --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    volumes:
      - minio_data:/data
    restart: unless-stopped
    networks:
      - huly-network

  account:
    image: hardcoreeng/account:${HULY_VERSION}
    ports:
      - 3000:3000
    environment:
      - SERVER_PORT=3000
      - SERVER_SECRET=${HULY_SECRET}
      - DB_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017
      - TRANSACTOR_URL=ws://transactor:3333;ws://${SERVER_ADDRESS}:3333
      - STORAGE_CONFIG=minio|minio?accessKey=${MINIO_ACCESS_KEY}&secretKey=${MINIO_SECRET_KEY}
      - FRONT_URL=http://front:8080
      - MODEL_ENABLED=*
      - ACCOUNTS_URL=http://${SERVER_ADDRESS}:3000
      - ACCOUNT_PORT=3000
    restart: unless-stopped
    networks:
      - mongodb-network
      - huly-network
      - elasticsearch-network

  workspace:
    image: hardcoreeng/workspace:${HULY_VERSION}
    environment:
      - SERVER_SECRET=${HULY_SECRET}
      - DB_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017
      - MONGO_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017
      - TRANSACTOR_URL=ws://transactor:3333;ws://${SERVER_ADDRESS}:3333
      - STORAGE_CONFIG=minio|minio?accessKey=${MINIO_ACCESS_KEY}&secretKey=${MINIO_SECRET_KEY}
      - MODEL_ENABLED=*
      - ACCOUNTS_URL=http://account:3000
      - NOTIFY_INBOX_ONLY=true
    restart: unless-stopped
    networks:
      - mongodb-network
      - huly-network
      - elasticsearch-network

  front:
    image: hardcoreeng/front:${HULY_VERSION}
    ports:
      - 8087:8080
    environment:
      - SERVER_PORT=8080
      - SERVER_SECRET=${HULY_SECRET}
      - ACCOUNTS_URL=http://${SERVER_ADDRESS}:3000
      - REKONI_URL=http://${SERVER_ADDRESS}:4004
      - CALENDAR_URL=http://${SERVER_ADDRESS}:8095
      - GMAIL_URL=http://${SERVER_ADDRESS}:8088
      - TELEGRAM_URL=http://${SERVER_ADDRESS}:8086
      - UPLOAD_URL=/files
      - ELASTIC_URL=http://elasticsearch:9100
      - COLLABORATOR_URL=ws://${SERVER_ADDRESS}:3078
      - STORAGE_CONFIG=minio|minio?accessKey=${MINIO_ACCESS_KEY}&secretKey=${MINIO_SECRET_KEY}
      - MONGO_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017
      - TITLE=Huly Self Hosted
      - DEFAULT_LANGUAGE=en
      - LAST_NAME_FIRST=true
    restart: unless-stopped
    networks:
      - mongodb-network
      - huly-network
      - elasticsearch-network

  collaborator:
    image: hardcoreeng/collaborator:${HULY_VERSION}
    ports:
      - 3078:3078
    environment:
      - COLLABORATOR_PORT=3078
      - SECRET=${HULY_SECRET}
      - ACCOUNTS_URL=http://account:3000
      - MONGO_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017
      - STORAGE_CONFIG=minio|minio?accessKey=${MINIO_ACCESS_KEY}&secretKey=${MINIO_SECRET_KEY}
    restart: unless-stopped
    networks:
      - mongodb-network
      - huly-network

  transactor:
    image: hardcoreeng/transactor:${HULY_VERSION}
    ports:
      - 3333:3333
    environment:
      - SERVER_PORT=3333
      - SERVER_SECRET=${HULY_SECRET}
      - SERVER_CURSOR_MAXTIMEMS=30000
      - ELASTIC_URL=http://elasticsearch:9100
      - ELASTIC_INDEX_NAME=huly_storage_index
      - DB_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017
      - MONGO_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017
      - METRICS_CONSOLE=false
      - METRICS_FILE=metrics.txt
      - STORAGE_CONFIG=minio|minio?accessKey=${MINIO_ACCESS_KEY}&secretKey=${MINIO_SECRET_KEY}
      - REKONI_URL=http://rekoni:4004
      - FRONT_URL=http://${SERVER_ADDRESS}:8087
      - ACCOUNTS_URL=http://account:3000
      - LAST_NAME_FIRST=true
    restart: unless-stopped
    networks:
      - mongodb-network
      - huly-network
      - elasticsearch-network

  rekoni:
    image: hardcoreeng/rekoni-service:${HULY_VERSION}
    ports:
      - 4004:4004
    environment:
      - SECRET=${HULY_SECRET}
    deploy:
      resources:
        limits:
          memory: 500M
    restart: unless-stopped
    networks:
      - huly-network

networks:
  huly-network:
    external: true
  mongodb-network:
    external: true
  elasticsearch-network:
    external: true

volumes:
  minio_data:
    external: true
