version: '3'

services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: unless-stopped
    networks:
      - nextcloud
      - redis_network
    depends_on:
      - nextclouddb
      - redis
    ports:
      - 8081:80
    volumes:
      - /portainer/Files/AppData/Config/Nextcloud/html:/var/www/html
      - /portainer/Files/AppData/Config/Nextcloud/custom_apps:/var/www/html/custom_apps
      - /portainer/Files/AppData/Config/Nextcloud/config:/var/www/html/config
      - /portainer/Files/AppData/Config/Nextcloud/data:/var/www/html/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dhaka
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=nextclouddb
      - REDIS_HOST=redis

  cron:
    image: nextcloud
    container_name: nextcloud-cron
    restart: unless-stopped
    networks:
      - nextcloud
      - redis_network
    depends_on:
      - nextcloud
      - nextclouddb
      - redis
    entrypoint: /cron.sh
    volumes:
      - /portainer/Files/AppData/Config/Nextcloud/html:/var/www/html
      - /portainer/Files/AppData/Config/Nextcloud/custom_apps:/var/www/html/custom_apps
      - /portainer/Files/AppData/Config/Nextcloud/config:/var/www/html/config
      - /portainer/Files/AppData/Config/Nextcloud/data:/var/www/html/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dhaka

  nextclouddb:
    image: mariadb
    container_name: nextcloud-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    networks:
      - nextcloud
    volumes:
      - /portainer/Files/AppData/Config/Nextcloud/nextclouddb:/var/lib/mysql
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dhaka
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}

  collabora:
    image: collabora/code
    container_name: collabora
    restart: unless-stopped
    networks:
      - nextcloud
      - redis_network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dhaka
      - password=${COLLABORA_PASSWORD}
      - username=${COLLABORA_USERNAME}
      - domain=${PUBLIC_URL}
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true
    volumes:
      - /usr/share/fonts/truetype:/opt/collaboraoffice/share/fonts/truetype/local:ro
    ports:
      - 9980:9980

networks:
  nextcloud:
    driver: bridge
    external: true
  redis_network:
    external: true
