version: "3"
services:
  minio:
    image: "minio/minio"
    command: server /data --address ":9000" --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    restart: unless-stopped
    networks:
      - huly-network

  account:
    image: hardcoreeng/account:${HULY_VERSION}
    ports:
      - 9193:9193
    environment:
      - SERVER_PORT=9193
      - SERVER_SECRET=${HULY_SECRET}
      - DB_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017
      - TRANSACTOR_URL=ws://transactor:9191;ws://${SERVER_ADDRESS}:9191
      - STORAGE_CONFIG=minio|minio?accessKey=${MINIO_ROOT_USER}&secretKey=${MINIO_ROOT_PASSWORD}
      - FRONT_URL=http://front:9195
      - MODEL_ENABLED=*
      - ACCOUNTS_URL=http://${SERVER_ADDRESS}:9193
      - ACCOUNT_PORT=9193
    restart: unless-stopped
    networks:
      - mongodb-network
      - huly-network

  workspace:
    image: hardcoreeng/workspace:${HULY_VERSION}
    environment:
      - SERVER_SECRET=${HULY_SECRET}
      - DB_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017
      - MONGO_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017
      - TRANSACTOR_URL=ws://transactor:9191;ws://${SERVER_ADDRESS}:9191
      - STORAGE_CONFIG=minio|minio?accessKey=${MINIO_ROOT_USER}&secretKey=${MINIO_ROOT_PASSWORD}
      - MODEL_ENABLED=*
      - ACCOUNTS_URL=http://account:9193
      - NOTIFY_INBOX_ONLY=true
    restart: unless-stopped
    networks:
      - mongodb-network
      - huly-network

  front:
    image: hardcoreeng/front:${HULY_VERSION}
    ports:
      - 9195:9195
    environment:
      - SERVER_PORT=9195
      - SERVER_SECRET=${HULY_SECRET}
      - ACCOUNTS_URL=http://${SERVER_ADDRESS}:9193
      - REKONI_URL=http://${SERVER_ADDRESS}:9190
      - CALENDAR_URL=http://${SERVER_ADDRESS}:8095
      - GMAIL_URL=http://${SERVER_ADDRESS}:8088
      - TELEGRAM_URL=http://${SERVER_ADDRESS}:8086
      - UPLOAD_URL=/files
      - ELASTIC_URL=http://elastic:${ELASTIC_SEARCH_PASSWORD}@172.16.234.51:9100 # to do: need to change static ip to container name
      - COLLABORATOR_URL=ws://${SERVER_ADDRESS}:9192
      - STORAGE_CONFIG=minio|minio?accessKey=${MINIO_ROOT_USER}&secretKey=${MINIO_ROOT_PASSWORD}
      - MONGO_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017
      - TITLE=Huly Self Hosted
      - DEFAULT_LANGUAGE=en
      - LAST_NAME_FIRST=true
    restart: unless-stopped
    networks:
      - mongodb-network
      - huly-network
      - elasticsearch-network

  collaborator:
    image: hardcoreeng/collaborator:${HULY_VERSION}
    ports:
      - 9192:9192
    environment:
      - COLLABORATOR_PORT=9192
      - SECRET=${HULY_SECRET}
      - ACCOUNTS_URL=http://account:9193
      - MONGO_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017
      - STORAGE_CONFIG=minio|minio?accessKey=${MINIO_ROOT_USER}&secretKey=${MINIO_ROOT_PASSWORD}
    restart: unless-stopped
    networks:
      - mongodb-network
      - huly-network

  transactor:
    image: hardcoreeng/transactor:${HULY_VERSION}
    ports:
      - 9191:9191
    environment:
      - SERVER_PORT=9191
      - SERVER_SECRET=${HULY_SECRET}
      - SERVER_CURSOR_MAXTIMEMS=30000
      - ELASTIC_URL=http://elastic:${ELASTIC_SEARCH_PASSWORD}@172.16.234.51:9100
      - ELASTIC_INDEX_NAME=huly_storage_index
      - DB_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017
      - MONGO_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017
      - METRICS_CONSOLE=false
      - METRICS_FILE=metrics.txt
      - STORAGE_CONFIG=minio|minio?accessKey=${MINIO_ROOT_USER}&secretKey=${MINIO_ROOT_PASSWORD}
      - REKONI_URL=http://rekoni:9190
      - FRONT_URL=http://${SERVER_ADDRESS}:9195
      - ACCOUNTS_URL=http://account:9193
      - LAST_NAME_FIRST=true
    restart: unless-stopped
    networks:
      - mongodb-network
      - huly-network
      - elasticsearch-network

  rekoni:
    image: hardcoreeng/rekoni-service:${HULY_VERSION}
    ports:
      - 9190:9190
    environment:
      - SECRET=${HULY_SECRET}
    deploy:
      resources:
        limits:
          memory: 500M
    restart: unless-stopped
    networks:
      - huly-network

networks:
  huly-network:
    external: true
  mongodb-network:
    external: true
  elasticsearch-network:
    external: true

volumes:
  minio_data:
    external: true
