version: "3.5"

services:
  penpot-frontend:
    image: "penpotapp/frontend:latest"
    restart: always
    ports:
      - ${PORT}:80
    volumes:
      - penpot_assets:/opt/data/assets
    depends_on:
      - penpot-backend
      - penpot-exporter
    networks:
      - penpot-network
    environment:
      - PENPOT_FLAGS=${PENPOT_FLAGS_FE}

  penpot-backend:
    image: "penpotapp/backend:latest"
    restart: always
    volumes:
      - penpot_assets:/opt/data/assets
    depends_on:
      - penpot-exporter
    networks:
      - penpot-network
      - postgres_network
      - redis_network
    environment:
      - PENPOT_FLAGS=${PENPOT_FLAGS_BE}
      - PENPOT_PUBLIC_URI=${PUBLIC_URI}
      - PENPOT_DATABASE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      - PENPOT_DATABASE_USERNAME=${POSTGRES_USER}
      - PENPOT_DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - PENPOT_REDIS_URI=redis://:${REDIS_PASSWORD}@redis:${REDIS_PORT}/0
      - PENPOT_ASSETS_STORAGE_BACKEND=assets-fs
      - PENPOT_STORAGE_ASSETS_FS_DIRECTORY=/opt/data/assets
      - PENPOT_TELEMETRY_ENABLED=${TELEMETRY_ENABLED}

  penpot-exporter:
    image: "penpotapp/exporter:latest"
    restart: always
    networks:
      - penpot-network
      - redis_network
    environment:
      - PENPOT_PUBLIC_URI=http://penpot-frontend
      - PENPOT_REDIS_URI=redis://:${REDIS_PASSWORD}@redis:${REDIS_PORT}/0

networks:
  penpot-network:
    external: true
  postgres_network:
    external: true
  redis_network:
    external: true

volumes:
  penpot_assets:
    external: true
