version: '3'

services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: unless-stopped
    networks:
      - cloud
    depends_on:
      - nextclouddb
      - redis
    ports:
      - 8081:80
    volumes:
      - ./html:/var/www/html
      - ./custom_apps:/var/www/html/custom_apps
      - ./config:/var/www/html/config
      - ./data:/var/www/html/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dhaka
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=dbpassword
      - MYSQL_HOST=nextclouddb
      - REDIS_HOST=redis
      # - OVERWRITEHOST=cloud.squarehealth.com.bd
      # - OVERWRITEPROTOCOL=https
      # - NEXTCLOUD_TRUSTED_DOMAINS=202.59.140.135

  cron:
    image: nextcloud
    container_name: nextcloud-cron
    restart: unless-stopped
    networks:
      - cloud
    depends_on:
      - nextcloud
      - nextclouddb
      - redis
    entrypoint: /cron.sh
    volumes:
      - ./html:/var/www/html
      - ./custom_apps:/var/www/html/custom_apps
      - ./config:/var/www/html/config
      - ./data:/var/www/html/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dhaka

  nextclouddb:
    image: mariadb
    container_name: nextcloud-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    networks:
      - cloud
    volumes:
      - ./nextclouddb:/var/lib/mysql
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dhaka
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_PASSWORD=dbpassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  collabora:
    image: collabora/code
    container_name: collabora
    restart: unless-stopped
    networks:
      - cloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dhaka
      - password=password
      - username=nextcloud
      - domain=cloud.squarehealth.com.bd|202.59.140.135
      #- extra_params=--o:ssl.enable=true
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true
    volumes:
      - /usr/share/fonts/truetype:/opt/collaboraoffice/share/fonts/truetype/local:ro
    ports:
      - 9980:9980

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - ./redis:/data
    networks:
      - cloud

networks:
  cloud:
    name: cloud
    driver: bridge